Use `. git-sghetti` instead of `. <(git-sghetti)`

diff --git a/bin/git-sghetti b/bin/git-sghetti
--- a/bin/git-sghetti
+++ b/bin/git-sghetti
@@ -1,24 +1,7 @@
 #!/bin/bash
 
-# define some vars
-prog="${0##*/}"
-SUBDIRECTORY_OK=Yes
-NONGIT_OK=Yes
-OPTIONS_KEEPDASHDASH=
-OPTIONS_STUCKLONG=
-OPTIONS_SPEC="\
-${prog/-/ } [url [...]]
-
-Take each git url and print the scheme, flavor, proto, user, host, and dir.
-If no <url>s are provided, the remote repository of the current branch is used.
---
-"
-
-# normalize options, set up shell functions, define $GIT_DIR, $GIT_OBJECT_DIRECTORY
-. "$(git --exec-path)/git-sh-setup"
-
-# use remote url if called with no args
-if [[ -z "$*" || "$*" == '--' ]]; then
+# prints the remote url
+remote_url() {
 	# figure out remote url for current branch
 	branch="$(git rev-parse --abbrev-ref HEAD)"
 	remote="$(git config --default origin "branch.$branch.remote")"
@@ -26,38 +9,20 @@ if [[ -z "$*" || "$*" == '--' ]]; then
 
 	# check if remote has a url
 	if [[ -z "$remote" ]]; then
-		echo exit 1
-		die "No remote configured for branch: $branch"
+		echo "No remote configured for branch: $branch" >&2
+		return 1
 	elif [[ -z "$url" ]]; then
-		echo exit 1
-		die "No url configured for remote: $remote"
+		echo "No url configured for remote: $remote" >&2
+		return 1
 	fi
 
-	# set url
-	set -- "$url"
-fi
+	echo "$url"
+}
 
-# parse options
-while (( $# )); do
-	case "$1" in
-		--)
-			shift
-			break
-		;;
-		-*)
-			echo exit 1
-			die "Unimplemented option (this is a bug): $1"
-		;;
-		*)
-			break
-		;;
-	esac
-	shift
-done
-
-# process each url
-i=0
-for url in "$@"; do
+# parses url and sets scheme, flavor, proto, etc.
+parse_url() {
+	# parse args
+	local url="$1"
 	scheme=
 	flavor=
 	proto=
@@ -98,16 +63,18 @@ for url in "$@"; do
 		dir="${BASH_REMATCH[3]}"
 		flavor=ssh
 	else
-		echo exit 1
-		die "Couldn't parse url: $url"
+		echo "Couldn't parse url: $url" >&2
+		return 1
 	fi
 
 	# use config to override flavor, user
+	local sghetti rule var condition val
+	local setvar value
 	while IFS=' ' read -r sghetti rule var condition val; do
 		if [[ $condition == equals && ${!var} == $val ]]; then
 			# set var to val
 			while IFS=' ' read -r setvar value; do
-				declare "$setvar=$value"
+				declare -g "$setvar=$value"
 			done < <( \
 				git config --get-regexp "^sghetti\.$rule\.set-(flavor|user)$" \
 				| sed "s/^sghetti\.$rule\.set-//"
@@ -120,7 +87,7 @@ for url in "$@"; do
 					value="${value//\\$i/${BASH_REMATCH[$i]}}"
 				done
 				# set var to val
-				declare "$setvar=$value"
+				declare -g "$setvar=$value"
 			done < <( \
 				git config --get-regexp "^sghetti\.$rule\.set-(flavor|user)$" \
 				| sed "s/^sghetti\.$rule\.set-//"
@@ -133,6 +100,62 @@ for url in "$@"; do
 		| sed 's/\./ /; s/\./ /; s/-/ /' \
 		| LC_ALL=C sort
 	)
+}
+
+# just set the url properties if this script was sourced
+if [[ "${BASH_SOURCE[0]}" != "$0" ]]; then
+	url="$(remote_url)" || exit
+	parse_url "$url" || exit
+	return
+fi
+
+# define some vars
+prog="${0##*/}"
+SUBDIRECTORY_OK=Yes
+NONGIT_OK=Yes
+OPTIONS_KEEPDASHDASH=
+OPTIONS_STUCKLONG=
+OPTIONS_SPEC="\
+${prog/-/ } [url [...]]
+
+Print the properties (scheme, flavor, proto, user, host, and dir) of each url.
+If no <url>s are provided, the remote repository of the current branch is used.
+If this script is sourced, define the properties as shell variables instead of
+printing them.
+--
+"
+
+# normalize options, set up shell functions, define $GIT_DIR, $GIT_OBJECT_DIRECTORY
+. "$(git --exec-path)/git-sh-setup"
+
+# use remote url if called with no args
+if [[ -z "$*" || "$*" == '--' ]]; then
+	url="$(remote_url)" || exit
+	set -- "$url"
+fi
+
+# parse options
+while (( $# )); do
+	case "$1" in
+		--)
+			shift
+			break
+		;;
+		-*)
+			die "Unimplemented option (this is a bug): $1"
+		;;
+		*)
+			break
+		;;
+	esac
+	shift
+done
+
+# process each url
+i=0
+for url in "$@"; do
+	# parse url
+	parse_url "$url"
 
 	# print each variable
 	((i++)) && echo
