Make git-sghetti's default url more consistent
Default to the remote push url. In a triangular workflow, the remote
pull url can be used by setting SGHETTI_UPSTREAM=pull as an env var.

diff --git a/bin/git-sghetti b/bin/git-sghetti
--- a/bin/git-sghetti
+++ b/bin/git-sghetti
@@ -3,16 +3,15 @@
 # prints the remote url
 remote_url() {
 	# figure out remote url for current branch
-	branch="$(git rev-parse --abbrev-ref HEAD 2>/dev/null)"
-	remote="$(git config --default origin "branch.$branch.remote")"
-	url="$(git config "remote.$remote.url")"
+	upstream='@{push}'
+	[[ -n $SGHETTI_UPSTREAM && $SGHETTI_UPSTREAM != push ]] && upstream='@{upstream}'
+	IFS=/ read remote branch \
+		<<< "$(git rev-parse --abbrev-ref "$upstream" 2>/dev/null)"
+	url="$(git ls-remote --get-url "$remote")"
 
 	# check if remote has a url
-	if [[ -z "$remote" ]]; then
-		echo "No remote configured for branch: $branch" >&2
-		return 1
-	elif [[ -z "$url" ]]; then
-		echo "No url configured for remote: $remote" >&2
+	if [[ -z "$url" ]]; then
+		echo "Couldn't determine upstream url." >&2
 		return 1
 	fi
 
@@ -124,7 +123,6 @@ ${prog/-/ } [url [...]]
 
 Print the properties (scheme, flavor, proto, user, host, and dir) of each url.
 If no <url>s are provided, the upstream remote of the current branch is used.
-If the current branch has no remote configured, 'origin' is used instead.
 
 If this script is sourced, define the url properties as shell variables instead
 of printing them.
